config/routes.rb
Rails.application.routes.draw do
  root 'links#index'

  resources :links, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]
    post :upvote, on: :member
    post :downvote, on: :member
  end

  get '/comments' => 'comments#index'
  get '/newest' => 'links#newest', as: :newest_links

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :votes

    scope :hottest, -> { order(hot_score: :desc) }
    scope :newest, -> { order(created_at: :desc) }

    validates :title,
              presence: true,
              uniqueness: { case_sensitive: false }
    validates :url,
              format: { with: %r{\Ahttps?://} },
              allow_blank: true

    def comment_count
      comments.length
    end

    def upvotes
      votes.sum(:upvote)
    end

    def downvotes
      votes.sum(:downvote)
    end

    def calc_hot_score
        points = upvotes - downvotes
        time_ago_in_hours = ((Time.now - created_at) / 3600).round
        score = hot_score(points, time_ago_in_hours)

        update_attributes(points: points, hot_score: score)
    end

    private
    def hot_score(points, time_ago_in_hours, gravity = 1.8)
        (points - 1) / (time_ago_in_hours + 2) ** gravity
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :links
    has_many :comments
    has_many :votes
    has_secure_password

    validates :username,
              presence: true,
              length: { minimum: 3 },
              uniqueness: { case_sensitive: false }

    validates :password, length: { minimum: 8 }

    def owns_link?(link)
      self == link.user
    end

    def owns_comment?(comment)
      self == comment.user
    end

    def upvote(link)
      votes.create(upvote: 1, link: link)
    end

    def upvoted?(link)
      votes.exists?(upvote: 1, link: link)
    end

    def downvote(link)
      votes.create(downvote: 1, link: link)
    end

    def downvoted?(link)
      votes.exists?(downvote: 1, link: link)
    end

    def remove_vote(link)
      votes.find_by(link: link).destroy
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :link
  validates :user_id, uniqueness: { scope: :link_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    def login(user)
      session[:user_id] = user.id
    end

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logout
      session.delete(:user_id)
      @current_user = nil
    end

    def logged_in?
      current_user.nil? ? false : true
    end

    helper_method :current_user, :logged_in?

    def prevent_unauthorized_user_access
      redirect_to root_path, notice: 'Sorry, you cannot access that page', status: :found unless logged_in?
    end

    def prevent_logged_in_user_access
      redirect_to root_path, notice: 'Sorry, you cannot access that page', status: :found if logged_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :prevent_unauthorized_user_access, except: :index
    before_action :set_variables, only: [:edit, :update, :destroy]
    def index
      @comments = Comment.all
    end

    def edit
      unless current_user.owns_comment?(@comment)
        redirect_to root_path, notice: 'Not authorized to edit this comment'
      end
    end

    def create
      @link = Link.find_by(id: params[:link_id])
      @comment = @link.comments.new(user: current_user, body: comment_params[:body])

      if @comment.save
        redirect_to @link, notice: 'Comment created'
      else
        redirect_to @link, notice: 'Comment was not saved. Ensure you have entered a comment'
      end
    end

    def update
      if @comment.update(comment_params)
        redirect_to @link, notice: 'Comment updated'
      else
        render :edit
      end
    end

    def destroy
      if current_user.owns_comment?(@comment)
        @comment.destroy
        redirect_to @link, notice: 'Comment deleted'
      else
        redirect_to @link, notice: 'Not authorized to delete this comment'
      end
    end
  private
    def set_variables
      @link = Link.find_by(id: params[:link_id])
      @comment = @link.comments.find_by(id: params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :prevent_unauthorized_user_access, except: [:show, :index]
#index
  def index
    @links = Link.hottest
  end
#newest
  def newest
    @links = Link.newest
  end
#new
  def new
    @link = Link.new
  end
#show
  def show
    @link = Link.find_by(id: params[:id])
    @comments = @link.comments
  end
#edit
  def edit
    perform_action(:edit) { |link| @link = link }
  end
#update
  def update
    @link = current_user.links.find_by(id: params[:id])

    if @link.update(link_params)
      redirect_to root_path, notice: 'Link successfully updated'
    else
      render :edit
    end
  end
#create
  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to root_path, notice: 'Link successfully created'
    else
      render :new
    end
  end
#destroy
  def destroy
    perform_action(:delete) do |link|
      link.destroy
      redirect_to root_path, notice: 'Link successfully deleted'
    end
  end
#upvote
  def upvote
    link = Link.find_by(id: params[:id])

    if current_user.upvoted?(link)
      current_user.remove_vote(link)
    elsif current_user.downvoted?(link)
      current_user.remove_vote(link)
      current_user.upvote(link)
    else
      current_user.upvote(link)
    end

    link.calc_hot_score
    redirect_to root_path
  end
#downvote
  def downvote
    link = Link.find_by(id: params[:id])

    if current_user.downvoted?(link)
      current_user.remove_vote(link)
    elsif current_user.upvoted?(link)
      current_user.remove_vote(link)
      current_user.downvote(link)
    else
      current_user.downvote(link)
    end

    link.calc_hot_score
    redirect_to root_path
  end

  private
#perform_action
  def perform_action(action)
    link = Link.find_by(id: params[:id])

    if current_user.owns_link?(link)
      yield(link) if block_given?
    else
      redirect_to root_path, notice: "Not authorized to #{action} this link"
    end
  end
#link_params
  def link_params
    params.require(:link).permit(:title, :url, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :prevent_logged_in_user_access, except: :destroy
  before_action :prevent_unauthorized_user_access, only: :destroy

  def new
  end

  def create
    user = User.find_by(username: login_params[:username])

    if user && user.authenticate(login_params[:password])
      login(user)
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:notice] = 'Invalid username / password combination'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out'
  end

  private

  def login_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :prevent_logged_in_user_access

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: 'Logged in'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<section class="edit-comment">
  <header>
    <h1>
      Edit comment
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= form_for :comment, url: link_comment_path(@link, @comment), method: :patch do |f| %>
        <%= render "shared/errors", object: @comment %>
        <div class="form-group">
          <%= f.text_area :body, class: "form-control", rows: 10, required: true %>
        </div>

        <div class="form-group">
          <%= f.button "edit comment", class: "btn btn-success" %>
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/comments/index.html.erb
<section class="sitewide-comments">
  <% @comments.each do |comment| %>
  <div class="comment">
    <p class="comment-owner">
      <strong>
        <%= comment.user.username %>
      </strong>

      <span class="comment-created small">
        <%= time_ago_in_words(comment.created_at) %> ago
      </span>

      <% if logged_in? && current_user.owns_comment?(comment) %>
      <span class="edit-comment">
        <%= link_to 'edit',  edit_link_comment_path(comment.link, comment) %>
      </span>

      <span class="delete-comment">
        <%= link_to 'delete', link_comment_path(comment.link, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
      <% end %>
    </p>

    <p>
      <%= comment.body %>
    </p>
  </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jumpnews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "shared/navbar" %>
    <main>
      <% if flash[:notice] %>
        <p class="alert alert-info">
          <%= flash[:notice] %>
        </p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <%= render "shared/errors", object: @link %>

  <div class="form-group">
    <%= f.text_field :title, required: true, class: "form-control", placeholder: "title" %>
  </div>

  <div class="form-group">
    <%= f.url_field :url, class: "form-control", placeholder: "url" %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: "form-control", placeholder: "description", rows: 15 %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="link">
  <div class="title">
    <%= link_to link.title, (link.url? ? link.url : link) %>

    <% if link.url? %>
      <span>
        ( <%= link.url %> )
      </span>
    <% end %>
  </div>

  <div class="metadata">
    <span class="points">
      <%= pluralize(link.points, 'point') %> by <%= link.user.username %>
    </span>

    <span class="time-created">
      <%= time_ago_in_words(link.created_at) %> ago
    </span>

    <span class="comment-count">
      <%= link_to pluralize(link.comment_count, 'comment'), link %>
    </span>

    <% if logged_in? && current_user.owns_link?(link) %>
      <span class="edit-link">
        <%= link_to "edit", edit_link_path(link) %>
      </span>

      <span class="delete-link">
        <%= link_to "delete", link, method: :delete, data: { confirm: "Are you sure?" } %>
      </span>
    <% end %>

    <% if logged_in? %>
      <span class="upvote-link">
        <%= link_to "upvote (#{link.upvotes})", upvote_link_path(link), method: :post %>
      </span>

      <span class="downvote-link">
        <%= link_to "downvote (#{link.downvotes})", downvote_link_path(link), method: :post %>
      </span>
    <% end %>
  </div>

</div>

app/views/links/edit.html.erb
<section class="edit-link">
  <header>
    <h1>
      Edit link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/index.html.erb
<section class="all-links">
  <%= render @links %>
</section>

app/views/links/new.html.erb
<section class="new-link">
  <header>
    <h1>
      submit a link
    </h1>
  </header>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/links/newest.html.erb
<section class="newest-links">
  <%= render @links %>
</section>

app/views/links/show.html.erb
<section class="link-thread">
  <header>
    <%= render @link %>

    <% if @link.description? %>
      <p>
        <%= @link.description %>
      </p>
    <% end %>

  </header>

  <% if logged_in? %>
    <div class="add-comment row">
      <div class="col-sm-6">
        <%= form_for :comment, url: link_comments_path(@link) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "The quick brown fox...", rows: 10, required: true %>
          </div>

          <div class="form-group">
            <%= f.button "add comment", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="all-comments row">
    <div class="col-sm-12">
      <% if @comments.present? %>
        <h3>Comments</h3>
      <% end %>

      <% @comments.each do |comment| %>
        <div class="comment">
          <p class="comment-owner">
            <strong>
              <%= comment.user.username %>
            </strong>

            <span class="comment-created small">
              <%= time_ago_in_words(comment.created_at) %> ago
            </span>

            <% if logged_in? && current_user.owns_comment?(comment) %>
              <span class="edit-comment">
                <%= link_to 'edit',  edit_link_comment_path(@link, comment) %>
              </span>

              <span class="delete-comment">
                <%= link_to 'delete', link_comment_path(@link, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              </span>
            <% end %>
          </p>

          <p>
            <%= comment.body %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul class="errors alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <%= link_to "jump news", root_path, class: "logo" %>

    <div class="navlinks">
      <%= link_to "new", newest_links_path %>
      <%= link_to "comments", comments_path %>

      <% unless logged_in? %>
        <%= link_to "signup", new_user_path %>
        <%= link_to "login", new_session_path %>
      <% end %>

      <% if logged_in? %>
        <%= link_to "submit a link", new_link_path %>
        <%= link_to "logout", sessions_path, method: :delete %>
      <% end %>
    </div>
  </nav>
</header>

app/views/users/new.html.erb
<section class="register-user">
  <header>
    <h1>
      Create a new Account
    </h1>

    <div class="row">
      <div class="col-sm-6">
        <%= form_for @user do |f| %>
        <%= render "shared/errors", object: @user %>
        <div class="form-group">
          <%= f.text_field :username, class: "form-control", required: true, minlength: 3, placeholder: "username" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control", required: true, minlength: 8, placeholder: "password" %>
        </div>

        <div class="form-group">
          <%= f.button "Register", class: "btn btn-success" %>
        </div>

        <% end %>
      </div>
    </div>
  </header>
</section>